# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - refs/tags/*

variables:
  major: 0
  minor: 0
  patch: 0
  revision: $[counter('versioncounter', 0)]
  system.debug: "true"
  githubOrganization: 'HoeflingSoftware'
  githubRepo: 'GitHub-Azure-DevOps-Tasks'

jobs:
- job: Build
  displayName: Build
  pool: 
    name: Hosted VS2017

  steps:
  - task: Npm@1
    displayName: 'npm install Azure DevOps CLI'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install tfx-cli -g'

  - powershell: |
      $config = Get-Content $(Build.SourcesDirectory)\vss-extension.json -raw | ConvertFrom-Json
      Write-Host "Original Config File"
      Write-Host $config
      $config.version = $env:VERSION
      Write-Host "Updated Config File"
      Write-Host "$config"
      $config | ConvertTo-Json | Set-Content $(Build.SourcesDirectory)\vss-extension.json
    env:
      VERSION: $(major).$(minor).$(patch).$(revision)
    displayName: Update Version Number

  - powershell: 'tfx extension create --manifest-globs $(Build.SourcesDirectory)\vss-extension.json'
    displayName: 'Build Extension Installer'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- job: Release
  dependsOn: Build
  displayName: Release
  pool:
    name: "Hosted VS2017"
  condition: and(succeeded(), startswith(variables['Build.SourceBranch'], 'refs/tags'))

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: drop
      downloadPath: $(System.DefaultWorkingDirectory)/artifacts

  - task: Npm@1
    displayName: 'npm install github-release-notes'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install github-release-notes -g'

  - powershell: 'gren release --username=$(githubOrganization) --token=$env:TOKEN --repo=$(githubRepo); exit $LASTEXITCODE'
    env:
      TOKEN: $(githubToken)
    displayName: 'Create GitHub Release'

  - powershell: 'gren changelog --override --username=$(githubOrganization) --token=$env:TOKEN --repo=$(githubRepo); exit $LASTEXITCODE'
    env:
      TOKEN: $(githubToken)
    displayName: 'Update CHANGELOG.md'

  - task: ArchiveFiles@2
    displayName: 'Archive VSIX'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/artifacts'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(githubRepo)_$(major).$(minor).$(patch).$(revision).zip'

  - task: hoefling-software.GitHubTasks.GitHubPublishReleaseArtifact.GitHubPublishReleaseArtifact@1
    displayName: GitHubReleaseArtifact
    inputs:
      githubRepo: $(githubRepo)
      githubOrganization: $(githubOrganization)
      githubToken: $(githubToken)
      artifact: '$(Build.ArtifactStagingDirectory)/$(githubRepo)_$(major).$(minor).$(patch).$(revision).zip'
      artifactDisplayName: 'GitHubTasks-$(major).$(minor).$(patch).$(revision).zip'