# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - refs/tags/*

variables:
  major: 1
  minor: 0
  patch: 0
  revision: $[counter('versioncounter', 0)]
  system.debug: "true"
  githubOrganization: 'HoeflingSoftware'
  githubRepo: 'GitHub-Azure-DevOps-Tasks'

jobs:
- job: Build
  displayName: Build
  pool: 
    name: Hosted VS2017

  steps:
  - task: Npm@1
    displayName: 'npm install Azure DevOps CLI'
    inputs:
      command: custom
      verbose: false
      customCommand: 'install tfx-cli -g'

  - powershell: |
      $config = Get-Content $(Build.SourcesDirectory)\vss-extension.json -raw | ConvertFrom-Json
      Write-Host "Original Config File"
      Write-Host $config
      $config.version = $(major).$(minor).$(patch).$(revision)
      Write-Host "Updated Config File"
      Write-Host "$config"
      $config | ConvertTo-Json | Set-Content $(Build.SourcesDirectory)\vss-extension.json
    displayName: Update Version Number

  - powershell: 'tfx extension create --manifest-globs $(Build.SourcesDirectory)\vss-extension.json'
    displayName: 'Build Extension Installer'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to Artifacts Staging Directory'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'